//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWCF_0508.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://RuAAService.co.kr/Product")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int BalanceField;
        
        private string AccountNameField;
        
        private System.DateTime AccountDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime AccountDate {
            get {
                return this.AccountDateField;
            }
            set {
                if ((this.AccountDateField.Equals(value) != true)) {
                    this.AccountDateField = value;
                    this.RaisePropertyChanged("AccountDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IBank")]
    public interface IBank {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetProduct", ReplyAction="http://tempuri.org/IBank/GetProductResponse")]
        BasicWCF_0508.ServiceReference2.AccountInfo GetProduct(int _id, string _name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetProduct", ReplyAction="http://tempuri.org/IBank/GetProductResponse")]
        System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountInfo> GetProductAsync(int _id, string _name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddMoney", ReplyAction="http://tempuri.org/IBank/AddMoneyResponse")]
        bool AddMoney(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/AddMoney", ReplyAction="http://tempuri.org/IBank/AddMoneyResponse")]
        System.Threading.Tasks.Task<bool> AddMoneyAsync(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/MinMoney", ReplyAction="http://tempuri.org/IBank/MinMoneyResponse")]
        bool MinMoney(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/MinMoney", ReplyAction="http://tempuri.org/IBank/MinMoneyResponse")]
        System.Threading.Tasks.Task<bool> MinMoneyAsync(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankChannel : BasicWCF_0508.ServiceReference2.IBank, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankClient : System.ServiceModel.ClientBase<BasicWCF_0508.ServiceReference2.IBank>, BasicWCF_0508.ServiceReference2.IBank {
        
        public BankClient() {
        }
        
        public BankClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BasicWCF_0508.ServiceReference2.AccountInfo GetProduct(int _id, string _name) {
            return base.Channel.GetProduct(_id, _name);
        }
        
        public System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountInfo> GetProductAsync(int _id, string _name) {
            return base.Channel.GetProductAsync(_id, _name);
        }
        
        public bool AddMoney(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money) {
            return base.Channel.AddMoney(_account, _money);
        }
        
        public System.Threading.Tasks.Task<bool> AddMoneyAsync(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money) {
            return base.Channel.AddMoneyAsync(_account, _money);
        }
        
        public bool MinMoney(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money) {
            return base.Channel.MinMoney(_account, _money);
        }
        
        public System.Threading.Tasks.Task<bool> MinMoneyAsync(BasicWCF_0508.ServiceReference2.AccountInfo _account, int _money) {
            return base.Channel.MinMoneyAsync(_account, _money);
        }
    }
}
