//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWCF_0508.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://RuAAService.co.kr/Product")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int BalanceField;
        
        private string AccountNameField;
        
        private System.DateTime AccountDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime AccountDate {
            get {
                return this.AccountDateField;
            }
            set {
                if ((this.AccountDateField.Equals(value) != true)) {
                    this.AccountDateField = value;
                    this.RaisePropertyChanged("AccountDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountList", Namespace="http://RuAAService.co.kr/Product")]
    [System.SerializableAttribute()]
    public partial class AccountList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccListIDField;
        
        private int AccIDField;
        
        private int InputMoneyField;
        
        private int OutputMoneyField;
        
        private int BalanceField;
        
        private System.DateTime DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccListID {
            get {
                return this.AccListIDField;
            }
            set {
                if ((this.AccListIDField.Equals(value) != true)) {
                    this.AccListIDField = value;
                    this.RaisePropertyChanged("AccListID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AccID {
            get {
                return this.AccIDField;
            }
            set {
                if ((this.AccIDField.Equals(value) != true)) {
                    this.AccIDField = value;
                    this.RaisePropertyChanged("AccID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int InputMoney {
            get {
                return this.InputMoneyField;
            }
            set {
                if ((this.InputMoneyField.Equals(value) != true)) {
                    this.InputMoneyField = value;
                    this.RaisePropertyChanged("InputMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int OutputMoney {
            get {
                return this.OutputMoneyField;
            }
            set {
                if ((this.OutputMoneyField.Equals(value) != true)) {
                    this.OutputMoneyField = value;
                    this.RaisePropertyChanged("OutputMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IBank")]
    public interface IBank {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/ConnectDB", ReplyAction="http://tempuri.org/IBank/ConnectDBResponse")]
        string ConnectDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/ConnectDB", ReplyAction="http://tempuri.org/IBank/ConnectDBResponse")]
        System.Threading.Tasks.Task<string> ConnectDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/MakeAccount", ReplyAction="http://tempuri.org/IBank/MakeAccountResponse")]
        bool MakeAccount(BasicWCF_0508.ServiceReference2.AccountInfo _account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/MakeAccount", ReplyAction="http://tempuri.org/IBank/MakeAccountResponse")]
        System.Threading.Tasks.Task<bool> MakeAccountAsync(BasicWCF_0508.ServiceReference2.AccountInfo _account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/DeleteAccount", ReplyAction="http://tempuri.org/IBank/DeleteAccountResponse")]
        bool DeleteAccount(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/DeleteAccount", ReplyAction="http://tempuri.org/IBank/DeleteAccountResponse")]
        System.Threading.Tasks.Task<bool> DeleteAccountAsync(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetAccCount", ReplyAction="http://tempuri.org/IBank/GetAccCountResponse")]
        int GetAccCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/GetAccCount", ReplyAction="http://tempuri.org/IBank/GetAccCountResponse")]
        System.Threading.Tasks.Task<int> GetAccCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/InputMoney", ReplyAction="http://tempuri.org/IBank/InputMoneyResponse")]
        bool InputMoney(int _id, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/InputMoney", ReplyAction="http://tempuri.org/IBank/InputMoneyResponse")]
        System.Threading.Tasks.Task<bool> InputMoneyAsync(int _id, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/OutputMoney", ReplyAction="http://tempuri.org/IBank/OutputMoneyResponse")]
        bool OutputMoney(int _id, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/OutputMoney", ReplyAction="http://tempuri.org/IBank/OutputMoneyResponse")]
        System.Threading.Tasks.Task<bool> OutputMoneyAsync(int _id, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAccount", ReplyAction="http://tempuri.org/IBank/SelectAccountResponse")]
        BasicWCF_0508.ServiceReference2.AccountInfo SelectAccount(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAccount", ReplyAction="http://tempuri.org/IBank/SelectAccountResponse")]
        System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountInfo> SelectAccountAsync(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAllAccount", ReplyAction="http://tempuri.org/IBank/SelectAllAccountResponse")]
        BasicWCF_0508.ServiceReference2.AccountInfo[] SelectAllAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAllAccount", ReplyAction="http://tempuri.org/IBank/SelectAllAccountResponse")]
        System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountInfo[]> SelectAllAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAllAccount1", ReplyAction="http://tempuri.org/IBank/SelectAllAccount1Response")]
        System.Data.DataTable SelectAllAccount1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAllAccount1", ReplyAction="http://tempuri.org/IBank/SelectAllAccount1Response")]
        System.Threading.Tasks.Task<System.Data.DataTable> SelectAllAccount1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAccountList", ReplyAction="http://tempuri.org/IBank/SelectAccountListResponse")]
        BasicWCF_0508.ServiceReference2.AccountList[] SelectAccountList(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAccountList", ReplyAction="http://tempuri.org/IBank/SelectAccountListResponse")]
        System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountList[]> SelectAccountListAsync(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAccountList1", ReplyAction="http://tempuri.org/IBank/SelectAccountList1Response")]
        System.Data.DataTable SelectAccountList1(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/SelectAccountList1", ReplyAction="http://tempuri.org/IBank/SelectAccountList1Response")]
        System.Threading.Tasks.Task<System.Data.DataTable> SelectAccountList1Async(int _id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankChannel : BasicWCF_0508.ServiceReference2.IBank, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankClient : System.ServiceModel.ClientBase<BasicWCF_0508.ServiceReference2.IBank>, BasicWCF_0508.ServiceReference2.IBank {
        
        public BankClient() {
        }
        
        public BankClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConnectDB() {
            return base.Channel.ConnectDB();
        }
        
        public System.Threading.Tasks.Task<string> ConnectDBAsync() {
            return base.Channel.ConnectDBAsync();
        }
        
        public bool MakeAccount(BasicWCF_0508.ServiceReference2.AccountInfo _account) {
            return base.Channel.MakeAccount(_account);
        }
        
        public System.Threading.Tasks.Task<bool> MakeAccountAsync(BasicWCF_0508.ServiceReference2.AccountInfo _account) {
            return base.Channel.MakeAccountAsync(_account);
        }
        
        public bool DeleteAccount(int _id) {
            return base.Channel.DeleteAccount(_id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAccountAsync(int _id) {
            return base.Channel.DeleteAccountAsync(_id);
        }
        
        public int GetAccCount() {
            return base.Channel.GetAccCount();
        }
        
        public System.Threading.Tasks.Task<int> GetAccCountAsync() {
            return base.Channel.GetAccCountAsync();
        }
        
        public bool InputMoney(int _id, int _money) {
            return base.Channel.InputMoney(_id, _money);
        }
        
        public System.Threading.Tasks.Task<bool> InputMoneyAsync(int _id, int _money) {
            return base.Channel.InputMoneyAsync(_id, _money);
        }
        
        public bool OutputMoney(int _id, int _money) {
            return base.Channel.OutputMoney(_id, _money);
        }
        
        public System.Threading.Tasks.Task<bool> OutputMoneyAsync(int _id, int _money) {
            return base.Channel.OutputMoneyAsync(_id, _money);
        }
        
        public BasicWCF_0508.ServiceReference2.AccountInfo SelectAccount(int _id) {
            return base.Channel.SelectAccount(_id);
        }
        
        public System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountInfo> SelectAccountAsync(int _id) {
            return base.Channel.SelectAccountAsync(_id);
        }
        
        public BasicWCF_0508.ServiceReference2.AccountInfo[] SelectAllAccount() {
            return base.Channel.SelectAllAccount();
        }
        
        public System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountInfo[]> SelectAllAccountAsync() {
            return base.Channel.SelectAllAccountAsync();
        }
        
        public System.Data.DataTable SelectAllAccount1() {
            return base.Channel.SelectAllAccount1();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SelectAllAccount1Async() {
            return base.Channel.SelectAllAccount1Async();
        }
        
        public BasicWCF_0508.ServiceReference2.AccountList[] SelectAccountList(int _id) {
            return base.Channel.SelectAccountList(_id);
        }
        
        public System.Threading.Tasks.Task<BasicWCF_0508.ServiceReference2.AccountList[]> SelectAccountListAsync(int _id) {
            return base.Channel.SelectAccountListAsync(_id);
        }
        
        public System.Data.DataTable SelectAccountList1(int _id) {
            return base.Channel.SelectAccountList1(_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SelectAccountList1Async(int _id) {
            return base.Channel.SelectAccountList1Async(_id);
        }
    }
}
